# @Author: Simon Dahan
# @Last Modified time: 2022-01-12 15:36:28
resolution:
  ico: 6
  sub_ico: 5

data:
  data_path:  /home/data/
  label_path: ../labels/dHCP/
  task: scan_age #scan_age #birth_age
  configuration: template #template #native
  split: train #train #validation
  channels: 4
  modality: cortical_metrics

output:
  folder: ../outputs/

sub_ico_1:
    num_patches: 80 
    num_vertices: 561 

sub_ico_2:
    num_patches: 320 
    num_vertices: 153 

sub_ico_3:
    num_patches: 1280
    num_vertices: 45
  
sub_ico_4:
    num_patches: 5120
    num_vertices: 15

sub_ico_5:
    num_patches: 20480
    num_vertices: 6




