# @Author: Simon Dahan
# @Date:   2022-05-10 15:00:42
# @Last Modified by:   Simon Dahan
# @Last Modified time: 2024-05-10 15:00:42

MODEL: sit
RECONSTRUCTION: True

mesh_resolution:
  ico_mesh: 6 #resolution of the input mesh
  ico_grid: 2 #resolution of the grid used to extract patches
  sampling: msm #sampling used for mesh resampling and patch extraction #msm or wb
  reorder: False #reorder the sequence of patches

ico_0_grid:
    num_patches: 20 
    num_vertices: 2145

ico_1_grid:
    num_patches: 80 
    num_vertices: 561 

ico_2_grid:
    num_patches: 320 
    num_vertices: 153 

ico_3_grid:
    num_patches: 1280
    num_vertices: 45

ico_4_grid:
    num_patches: 5120
    num_vertices: 15

ico_5_grid:
    num_patches: 20480
    num_vertices: 5

data:
  path_to_data: /home/sd20/data/
  path_to_template: /home/sd20/data/template_spheres
  dataset: dHCP #dHCP, HCP, UKB
  dataloader: metrics #metrics, numpy
  task: scan_age #scan_age, birth_age
  configuration: template
  masking: True #for dHCP only; True to mask the cut. 
  hemi: half #half, full
  normalise: sub-standardise #standardise-vertex-wise,standardise-channel-wise,False, normalise, standardise
  modality: cortical_metrics #cortical_metrics, fMRI
  clipping: True #True, False
  subject: CC00749XX24 #CC00749XX24
  sess: 2600 # for dHCP only

transformer:
  dim: 192 #192, 384, 768
  depth: 12 #12, 12, 12
  heads: 3 #3, 6, 12
  mlp_dim: 768 #768, 1536, 3072 ## 4*dim according to DeiT
  pool: 'cls'  # or 'mean'
  num_classes: 1
  channels: [0,1,2,3]
  dim_head: 64 #64
  dropout: 0.
  emb_dropout: 0.
  use_pos_embedding: 'sin-cos' #False, True, 'sin-cos', 'trainable'
  use_class_token: False #for mae:True (but not used)
  trainable_pos_emb: False #False #only for use_pos_embedding=trainable
  no_class_token_emb: True #for vsMAE set to TRUE! not using classification token position embedding
  init_weights_layers: False #True

training:
  gpu: 0
  bs: 1
  bs_val: 1
  sampler: False
  use_cross_validation: False
  use_confounds: False
  path_from_ckpt: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_2/template/no_augmentation/2022-10-26-14:40:22-tiny-finetune/ #90%
