# @Author: Simon Dahan @SD3004
# @Date:   31-08-2022 01:00:00

MODEL: ms-sit
SCRIPT: train
RECONSTRUCTION: False
distributed_training: False

##################################  DATA & TASK  ##################################

mesh_resolution:
  ico_mesh: 6 #resolution of the input mesh
  ico_grid: 5 #resolution of the grid used to extract patches
  sampling: msm #sampling used for mesh resampling and patch extraction #msm or wb
  reorder: True #reorder the sequence of patches

ico_0_grid:
    num_patches: 20 
    num_vertices: 2145

ico_1_grid:
    num_patches: 80 
    num_vertices: 561 

ico_2_grid:
    num_patches: 320 
    num_vertices: 153 

ico_3_grid:
    num_patches: 1280
    num_vertices: 45

ico_4_grid:
    num_patches: 5120
    num_vertices: 15

ico_5_grid:
    num_patches: 20480
    num_vertices: 6

data:
  path_to_data: /home/sd20/data/ #/drive/data #/drive/data, /home/sd20/data/
  path_to_template: /home/sd20/data/template_spheres
  path_to_workdir: /home/sd20/workspace/transformers
  dataset: dHCP #dHCP, HCP, UKB
  dataloader: metrics #metrics, numpy
  task: scan_age #scan_age, birth_age, sex, fluid_intelligence
  configuration: template #template, native
  masking: False #True to mask the cut. 
  hemi: half #half, full
  hemi_part: all
  normalise: sub-standardise #normalise,standardise, False
  modality: cortical_metrics #cortical_metrics, fMRI, memory_task, rsns[UKB;msmsulc], 3T_tfMRI_MOTOR, 3T_tfMRI_STORY, 3T_tfMRI_SOCIAL, 3T_tfMRI_WM
  registration: msmall #msmall, msmsulc
  clipping: False #True, False
  folder_to_dhcp: metrics/ico_6_msm/base/regression_{}_space_features
  subset: False

logging:
  folder_to_save_model: "{}/logs/{}/{}/{}/MS-SiT/ico_grid_{}/{}" #{dataset},{modality},{task},{grid resolution},{configuration}

###################################  MODEL  ####################################

transformer:
  dim: 96 #96, 48
  depth: [2,2,6,2] # [1,1,3,1] [2,2,6,2] number of blocks per layer
  heads: [3,6,12,24] # number of head per layer
  channels:  [0,1] #[0,1] for working memory and [0,1,2,3] for cortical metrics, rsns [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40], [UKB;rsns] [3,5,8,9,10] 
  window_size: [64,64,64,320] #320,80, [64,64,64,320], [320,320,320,80]
  window_size_factor: 4
  mlp_ratio: 4
  num_classes: 1
  dropout: 0.0
  attention_dropout: 0.0
  drop_path_rate: 0.1 #0.1 default to try
  use_pos_emb: False
  shifted_attention: False
  
##################################  TRAINING  ###################################

training:
  LR: 0.0001
  bs: 28
  bs_val: 1
  epochs: 500
  val_epoch: 5
  log_training_epoch: 1 #default 5, fMRI 1
  gpu: 1
  loss: mse #mse, l1
  testing: True
  init_weights: False #ssl, imagenet or False
  finetuning: True
  save_ckpt: True
  use_confounds: False
  early_stopping: 300 # validation steps
  sampler: False
  cv_split: [1,2,3,4,5]
  use_cross_validation: True #True

augmentation: # prob of augmentation techniques need to sum to 1
  prob_augmentation: 0.0  #probability of using any of the augmentation technique; 0.0 to not use any augmentation
  prob_rotation: 0.5 #use rotation
  max_abs_deg_rotation: 30
  prob_warping: 0.5 #use non-linear warping
  prob_shuffle: 0.0 #use shuffling of patches
  warp_ico: 2

##################################  OPTIMISATION  ##################################
  
optimisation:
  optimiser: SGD
  use_scheduler: False
  scheduler: CosineDecay  # CosineDecay, StepLR, ReduceLROnPlateau
  warmup: False
  nbr_step_warmup: 500 #iterations

SGD:
  weight_decay: 0.1 #default 0.0
  momentum: 0.9 #default 0.0
  nesterov: False

Adam:
  weight_decay: 0.0  #default 0.0

AdamW:
  weight_decay: 0.01  #default 0.01

####################################  SCHEDULER ####################################

StepLR: 
  stepsize: 100
  decay: 0.5

CosineDecay:
  T_max: 20  # number of iteration to go from high to low
  eta_min: 0.000003  #minimum learning rate

####################################################################################

